version: "3"
services:
  web:
    build: app
    ports:
      - 8000:8000
    networks:
      testnet:
        ipv4_address: 172.26.0.3
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port", 8000
    volumes:
      - .:/code
networks:
  testnet:
    external: true